apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  selector: 
    app: my-app
    version: "2.0.0"
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 31000


